name: CI/CD Pipeline

on:
  push:
    paths:
      - 'src/train.py'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build model
      run: python src/train.py

    - name: Test model
      run: python src/test.py
